BCH_MVC_VS2013/BCH_MVC/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Threading.Tasks;
using System.Web.Mvc;
using BCH_MVC.Models;

namespace BCH_MVC.Controllers
{
    public class UserAccountController : Controller
    {
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(AccountRegister model)
        {
            DBHelper db = new DBHelper();
            var UserId = model.UserId;
            var Pwd = model.Pwd;
            //判断用户名是否存在
            if (!db.UserExist(UserId))
            {
                var cmd = "Insert into UserAccount(UserId,Pwd) values('"+UserId+"','"+Pwd+"')";
                db.SqlExcute(cmd);
                return Redirect("Login");
            }
            else
            {
                Response.Write("<script>alert('账号已存在~~~ ')</script>");
                return View();
            }
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Login(AccountLogin model)
        {
            DBHelper db = new DBHelper();
            var uid = model.UserId;
            var pwd = model.Pwd;
            Session["UserId"] = uid;
            if (db.UserCorrect(uid,pwd))
            {
                return Redirect("~/Home/Index");
            }
            else
            {
                Response.Write("<script>alert('用户名或密码不正确~~~ ')</script>");
                return View();
            }

        }
    }
}

BCH_MVC_VS2013/BCH_MVC/Views/UserAccount/Login.cshtml
@model BCH_MVC.Models.AccountLogin
@{
    ViewBag.Title = "Login";
}

@using (Html.BeginForm("Login", "UserAccount", FormMethod.Post))
{
    <table align="center">
        <tr>
            <td>
                <h2>Login</h2>
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(m => m.UserId):
            </td>
            <td>
                @Html.TextBoxFor(m => m.UserId)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(m => m.Pwd):

            </td>
            <td>
                @Html.PasswordFor(m => m.Pwd)
            </td>
        </tr>
        <tr>
            <td align="center">
                <input type="submit" value="登陆" />
            </td>
            <td align="center">
                @Html.ActionLink("注册","Register","UserAccount")
               
            </td>
        </tr>
    </table>
}

BCH_MVC_VS2013/BCH_MVC/Views/UserAccount/Register.cshtml
@model BCH_MVC.Models.AccountRegister
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Register", "UserAccount", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <table align="center">
        <tr>
            <td>
                <h2>Register</h2>
            </td>
        </tr>
        <tr> 
            <td>
                @Html.LabelFor(m => m.UserId)
            </td>
            <td>
                @Html.TextBoxFor(m => m.UserId)<br />
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(m => m.Pwd)
            </td>
            <td>
                @Html.PasswordFor(m => m.Pwd)<br />
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(m => m.Pwd_Confirm)
                
            </td>
            <td>
                @Html.PasswordFor(m => m.Pwd_Confirm)<br />
            </td>
        </tr>
        <tr>
            <td align="center">
                <input type="submit" value="注册" />
            </td>
        </tr>
    </table>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}